import { StyleSheet } from 'react-native';
import { s, vs } from 'react-native-size-matters';

export const TagsStyles = {
	h1: {
		fontSize: 24,
		fontWeight: 'bold',
		marginBottom: 12,
		marginTop: 24,
	},
	h2: {
		fontSize: 20,
		fontWeight: 'bold',
		marginBottom: 10,
		marginTop: 20,
	},
	h3: {
		fontSize: 18,
		fontWeight: 'bold',
		marginBottom: 8,
		marginTop: 18,
	},
	p: {
		fontSize: 16,
		lineHeight: 24,
		marginBottom: 12,
	},
	pre: {
		backgroundColor: '#f6f6f6',
		padding: 12,
		borderRadius: 6,
		color: '#333',
		overflow: 'hidden', // ✅ fix: "scroll" is invalid
	},
	code: {
		fontSize: 14,
		backgroundColor: '#eee',
		padding: 4,
		borderRadius: 4,
	},
	img: {
		alignSelf: 'center',
		marginVertical: 12,
	},
	figcaption: {
		textAlign: 'center',
		fontSize: 14,
		fontStyle: 'italic',
		marginTop: 4,
		color: '#666',
	},
	ul: {
		marginVertical: 12,
		paddingLeft: 20,
	},
	ol: {
		marginVertical: 12,
		paddingLeft: 20,
	},
	li: {
		fontSize: 16,
		lineHeight: 24,
		marginBottom: 6,
	},
	blockquote: {
		borderLeftWidth: 4,
		borderLeftColor: '#ccc',
		paddingLeft: 12,
		color: '#555',
		fontStyle: 'italic',
		marginVertical: 12,
	},
} as const;

export const commonStyles = StyleSheet.create({
	shadow: {
		// IOS
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.25,
		shadowRadius: 3.84,

		// Android
		elevation: 4,
	},

	// Border Radius
	roundedFull: {
		borderRadius: 9999,
	},
	roundedLg: {
		borderRadius: s(8),
	},
	rounded2xl: {
		borderRadius: s(16),
	},

	// Padding (1–10)
	p1: { padding: s(4) },
	p2: { padding: s(8) },
	p3: { padding: s(12) },
	p4: { padding: s(16) },
	p5: { padding: s(20) },
	p6: { padding: s(24) },
	p7: { padding: s(28) },
	p8: { padding: s(32) },
	p9: { padding: s(36) },
	p10: { padding: s(40) },

	pt1: { paddingTop: vs(4) },
	pt2: { paddingTop: vs(8) },
	pt3: { paddingTop: vs(12) },
	pt4: { paddingTop: vs(16) },
	pt5: { paddingTop: vs(20) },
	pt6: { paddingTop: vs(24) },
	pt7: { paddingTop: vs(28) },
	pt8: { paddingTop: vs(32) },
	pt9: { paddingTop: vs(36) },
	pt10: { paddingTop: vs(40) },

	pb1: { paddingBottom: vs(4) },
	pb2: { paddingBottom: vs(8) },
	pb3: { paddingBottom: vs(12) },
	pb4: { paddingBottom: vs(16) },
	pb5: { paddingBottom: vs(20) },
	pb6: { paddingBottom: vs(24) },
	pb7: { paddingBottom: vs(28) },
	pb8: { paddingBottom: vs(32) },
	pb9: { paddingBottom: vs(36) },
	pb10: { paddingBottom: vs(40) },

	pl1: { paddingLeft: s(4) },
	pl2: { paddingLeft: s(8) },
	pl3: { paddingLeft: s(12) },
	pl4: { paddingLeft: s(16) },
	pl5: { paddingLeft: s(20) },
	pl6: { paddingLeft: s(24) },
	pl7: { paddingLeft: s(28) },
	pl8: { paddingLeft: s(32) },
	pl9: { paddingLeft: s(36) },
	pl10: { paddingLeft: s(40) },

	pr1: { paddingRight: s(4) },
	pr2: { paddingRight: s(8) },
	pr3: { paddingRight: s(12) },
	pr4: { paddingRight: s(16) },
	pr5: { paddingRight: s(20) },
	pr6: { paddingRight: s(24) },
	pr7: { paddingRight: s(28) },
	pr8: { paddingRight: s(32) },
	pr9: { paddingRight: s(36) },
	pr10: { paddingRight: s(40) },

	px1: { paddingHorizontal: s(4) },
	px2: { paddingHorizontal: s(8) },
	px3: { paddingHorizontal: s(12) },
	px4: { paddingHorizontal: s(16) },
	px5: { paddingHorizontal: s(20) },
	px6: { paddingHorizontal: s(24) },
	px7: { paddingHorizontal: s(28) },
	px8: { paddingHorizontal: s(32) },
	px9: { paddingHorizontal: s(36) },
	px10: { paddingHorizontal: s(40) },

	py1: { paddingVertical: vs(4) },
	py2: { paddingVertical: vs(8) },
	py3: { paddingVertical: vs(12) },
	py4: { paddingVertical: vs(16) },
	py5: { paddingVertical: vs(20) },
	py6: { paddingVertical: vs(24) },
	py7: { paddingVertical: vs(28) },
	py8: { paddingVertical: vs(32) },
	py9: { paddingVertical: vs(36) },
	py10: { paddingVertical: vs(40) },

	// Margin (1–10)
	m1: { margin: s(4) },
	m2: { margin: s(8) },
	m3: { margin: s(12) },
	m4: { margin: s(16) },
	m5: { margin: s(20) },
	m6: { margin: s(24) },
	m7: { margin: s(28) },
	m8: { margin: s(32) },
	m9: { margin: s(36) },
	m10: { margin: s(40) },

	mt1: { marginTop: vs(4) },
	mt2: { marginTop: vs(8) },
	mt3: { marginTop: vs(12) },
	mt4: { marginTop: vs(16) },
	mt5: { marginTop: vs(20) },
	mt6: { marginTop: vs(24) },
	mt7: { marginTop: vs(28) },
	mt8: { marginTop: vs(32) },
	mt9: { marginTop: vs(36) },
	mt10: { marginTop: vs(40) },

	mb1: { marginBottom: vs(4) },
	mb2: { marginBottom: vs(8) },
	mb3: { marginBottom: vs(12) },
	mb4: { marginBottom: vs(16) },
	mb5: { marginBottom: vs(20) },
	mb6: { marginBottom: vs(24) },
	mb7: { marginBottom: vs(28) },
	mb8: { marginBottom: vs(32) },
	mb9: { marginBottom: vs(36) },
	mb10: { marginBottom: vs(40) },

	ml1: { marginLeft: s(4) },
	ml2: { marginLeft: s(8) },
	ml3: { marginLeft: s(12) },
	ml4: { marginLeft: s(16) },
	ml5: { marginLeft: s(20) },
	ml6: { marginLeft: s(24) },
	ml7: { marginLeft: s(28) },
	ml8: { marginLeft: s(32) },
	ml9: { marginLeft: s(36) },
	ml10: { marginLeft: s(40) },

	mr1: { marginRight: s(4) },
	mr2: { marginRight: s(8) },
	mr3: { marginRight: s(12) },
	mr4: { marginRight: s(16) },
	mr5: { marginRight: s(20) },
	mr6: { marginRight: s(24) },
	mr7: { marginRight: s(28) },
	mr8: { marginRight: s(32) },
	mr9: { marginRight: s(36) },
	mr10: { marginRight: s(40) },

	mx1: { marginHorizontal: s(4) },
	mx2: { marginHorizontal: s(8) },
	mx3: { marginHorizontal: s(12) },
	mx4: { marginHorizontal: s(16) },
	mx5: { marginHorizontal: s(20) },
	mx6: { marginHorizontal: s(24) },
	mx7: { marginHorizontal: s(28) },
	mx8: { marginHorizontal: s(32) },
	mx9: { marginHorizontal: s(36) },
	mx10: { marginHorizontal: s(40) },

	my1: { marginVertical: vs(4) },
	my2: { marginVertical: vs(8) },
	my3: { marginVertical: vs(12) },
	my4: { marginVertical: vs(16) },
	my5: { marginVertical: vs(20) },
	my6: { marginVertical: vs(24) },
	my7: { marginVertical: vs(28) },
	my8: { marginVertical: vs(32) },
	my9: { marginVertical: vs(36) },
	my10: { marginVertical: vs(40) },
});

export const FlashMessageStyles = StyleSheet.create({
	flashMessage: {
		opacity: 0.9,
		alignItems: 'center',
	},
	flashTitle: {
		fontWeight: 'bold',
		fontSize: 18,
	},
	flashText: {
		fontStyle: 'italic',
		fontSize: 15,
	},
});
