ALTER TABLE "users" DROP CONSTRAINT "users_department_id_fkey";
ALTER TABLE "users" DROP CONSTRAINT "users_updated_by_fkey";
ALTER TABLE "users" DROP CONSTRAINT "users_created_by_fkey";
ALTER TABLE "device_tokens" DROP CONSTRAINT "device_tokens_user_id_fkey";
ALTER TABLE "user_preferences" DROP CONSTRAINT "user_preferences_user_id_fkey";
ALTER TABLE "registrars" DROP CONSTRAINT "registrars_updated_by_fkey";
ALTER TABLE "registrars" DROP CONSTRAINT "registrars_deleted_by_fkey";
ALTER TABLE "registrars" DROP CONSTRAINT "registrars_created_by_fkey";
ALTER TABLE "products" DROP CONSTRAINT "products_updated_by_fkey";
ALTER TABLE "products" DROP CONSTRAINT "products_deleted_by_fkey";
ALTER TABLE "products" DROP CONSTRAINT "products_created_by_fkey";
ALTER TABLE "orders" DROP CONSTRAINT "orders_user_id_fkey";
ALTER TABLE "orders" DROP CONSTRAINT "orders_updated_by_fkey";
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_order_id_fkey";
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_product_id_fkey";
ALTER TABLE "payments" DROP CONSTRAINT "payments_order_id_fkey";
ALTER TABLE "payments" DROP CONSTRAINT "payments_updated_by_fkey";
ALTER TABLE "payments" DROP CONSTRAINT "payments_created_by_fkey";
ALTER TABLE "blogs" DROP CONSTRAINT "blogs_author_fkey";
ALTER TABLE "blogs" DROP CONSTRAINT "blogs_updated_by_fkey";
ALTER TABLE "blogs" DROP CONSTRAINT "blogs_deleted_by_fkey";
ALTER TABLE "blogs" DROP CONSTRAINT "blogs_created_by_fkey";
-- ALTER TABLE "blog_views" DROP CONSTRAINT "blog_views_blog_id_fkey";
-- ALTER TABLE "companies" DROP CONSTRAINT "companies_deleted_by_fkey";
-- ALTER TABLE "event_speakers" DROP CONSTRAINT "event_speakers_deleted_by_fkey";
ALTER TABLE "events" DROP CONSTRAINT "events_updated_by_fkey";
ALTER TABLE "events" DROP CONSTRAINT "events_deleted_by_fkey";
ALTER TABLE "events" DROP CONSTRAINT "events_created_by_fkey";
ALTER TABLE "event_registrants" DROP CONSTRAINT "event_registrants_event_id_fkey";
ALTER TABLE "news_updates" DROP CONSTRAINT "news_updates_updated_by_fkey";
ALTER TABLE "news_updates" DROP CONSTRAINT "news_updates_deleted_by_fkey";
ALTER TABLE "news_updates" DROP CONSTRAINT "news_updates_created_by_fkey";
ALTER TABLE "news_letters" DROP CONSTRAINT "news_letters_updated_by_fkey";
ALTER TABLE "news_letters" DROP CONSTRAINT "news_letters_deleted_by_fkey";
ALTER TABLE "news_letters" DROP CONSTRAINT "news_letters_created_by_fkey";
ALTER TABLE "job_postings" DROP CONSTRAINT "job_postings_department_id_fkey";
ALTER TABLE "job_postings" DROP CONSTRAINT "job_postings_updated_by_fkey";
ALTER TABLE "job_postings" DROP CONSTRAINT "job_postings_deleted_by_fkey";
ALTER TABLE "job_postings" DROP CONSTRAINT "job_postings_created_by_fkey";
ALTER TABLE "job_applications" DROP CONSTRAINT "job_applications_job_id_fkey";
ALTER TABLE "job_applications" DROP CONSTRAINT "job_applications_updated_by_fkey";

DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS device_tokens;
DROP TABLE IF EXISTS user_preferences;
DROP TABLE IF EXISTS registrars;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS blogs;
-- DROP TABLE IF EXISTS blog_views;
DROP TABLE IF EXISTS companies;
DROP TABLE IF EXISTS event_speakers;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS event_registrants;
DROP TABLE IF EXISTS news_updates;
DROP TABLE IF EXISTS news_letters;
DROP TABLE IF EXISTS job_postings;
DROP TABLE IF EXISTS job_applications;